export const VENUE_CAT_DETAILS_REQUEST = "VENUE_CAT_DETAILS_REQUEST"
export const VENUE_CAT_DETAILS_SUCCESS = "VENUE_CAT_DETAILS_SUCCESS"
export const VENUE_CAT_DETAILS_FAIL = "VENUE_CAT_DETAILS_FAIL"

export const DELETE_CATERER_REQUEST = "DELETE_CATERER_REQUEST"
export const DELETE_CATERER_SUCCESS = "DELETE_CATERER_SUCCESS"
export const DELETE_CATERER_FAIL = "DELETE_CATERER_FAIL"
export const DELETE_CATERER_RESET = "DELETE_CATERER_RESET"

export const ALL_CATERER_REQUEST = "ALL_CATERER_REQUEST"
export const ALL_CATERER_SUCCESS = "ALL_CATERER_SUCCESS"  
export const ALL_CATERER_FAIL = "ALL_CATERER_FAIL"

export const UPDATE_CATERER_REQUEST = "UPDATE_CATERER_REQUEST"
export const UPDATE_CATERER_SUCCESS = "UPDATE_CATERER_SUCCESS"
export const UPDATE_CATERER_FAIL = "UPDATE_CATERER_FAIL"
export const UPDATE_CATERER_RESET = "UPDATE_CATERER_RESET"

export const MANAGER_CATERER_REQUEST = "MANAGER_CATERER_REQUEST"
export const MANAGER_CATERER_SUCCESS = "MANAGER_CATERER_SUCCESS"
export const MANAGER_CATERER_FAIL = "MANAGER_CATERER_FAIL"

export const CREATE_CATERER_REQUEST = "CREATE_CATERER_REQUEST"
export const CREATE_CATERER_SUCCESS = "CREATE_CATERER_SUCCESS"
export const CREATE_CATERER_FAIL = "CREATE_CATERER_FAIL"
export const CREATE_CATERER_RESET = "CREATE_CATERER_RESET"

export const CATERER_DETAILS_REQUEST = "CATERER_DETAILS_REQUEST"
export const CATERER_DETAILS_SUCCESS = "CATERER_DETAILS_SUCCESS"
export const CATERER_DETAILS_FAIL = "CATERER_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
