export const DELETE_DECORATION_REQUEST = "DELETE_DECORATION_REQUEST"
export const DELETE_DECORATION_SUCCESS = "DELETE_DECORATION_SUCCESS"
export const DELETE_DECORATION_FAIL = "DELETE_DECORATION_FAIL"
export const DELETE_DECORATION_RESET = "DELETE_DECORATION_RESET"

export const ALL_DECORATION_REQUEST = "ALL_DECORATION_REQUEST"
export const ALL_DECORATION_SUCCESS = "ALL_DECORATION_SUCCESS"
export const ALL_DECORATION_FAIL = "ALL_DECORATION_FAIL"

export const UPDATE_DECORATION_REQUEST = "UPDATE_DECORATION_REQUEST"
export const UPDATE_DECORATION_SUCCESS = "UPDATE_DECORATION_SUCCESS"
export const UPDATE_DECORATION_FAIL = "UPDATE_DECORATION_FAIL"
export const UPDATE_DECORATION_RESET = "UPDATE_DECORATION_RESET"

export const MANAGER_DECORATION_REQUEST = "MANAGER_DECORATION_REQUEST"
export const MANAGER_DECORATION_SUCCESS = "MANAGER_DECORATION_SUCCESS"
export const MANAGER_DECORATION_FAIL = "MANAGER_DECORATION_FAIL"

export const CREATE_DECORATION_REQUEST = "CREATE_DECORATION_REQUEST"
export const CREATE_DECORATION_SUCCESS = "CREATE_DECORATION_SUCCESS"
export const CREATE_DECORATION_FAIL = "CREATE_DECORATION_FAIL"
export const CREATE_DECORATION_RESET = "CREATE_DECORATION_RESET"

export const VENUE_DECORATION_DETAILS_REQUEST = "VENUE_DECORATION_DETAILS_REQUEST"
export const VENUE_DECORATION_DETAILS_SUCCESS = "VENUE_DECORATION_DETAILS_SUCCESS"
export const VENUE_DECORATION_DETAILS_FAIL = "VENUE_DECORATION_DETAILS_FAIL"

export const DECORATION_DETAILS_REQUEST = "DECORATION_DETAILS_REQUEST"
export const DECORATION_DETAILS_SUCCESS = "DECORATION_DETAILS_SUCCESS"
export const DECORATION_DETAILS_FAIL = "DECORATION_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
