export const MY_EVENTS_REQUEST = "MY_EVENTS_REQUEST"
export const MY_EVENTS_SUCCESS = "MY_EVENTS_SUCCESS"
export const MY_EVENTS_FAIL = "MY_EVENTS_FAIL"

export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST"
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS"
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL"

export const MANAGER_EVENTS_REQUEST = "MANAGER_EVENTS_REQUEST";
export const MANAGER_EVENTS_SUCCESS = "MANAGER_EVENTS_SUCCESS";
export const MANAGER_EVENTS_FAIL = "MANAGER_EVENTS_FAIL";

export const ALL_EVENTS_REQUEST = "ALL_EVENTS_REQUEST";
export const ALL_EVENTS_SUCCESS = "ALL_EVENTS_SUCCESS";
export const ALL_EVENTS_FAIL = "ALL_EVENTS_FAIL";

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_RESET = "UPDATE_EVENT_RESET";
export const UPDATE_EVENT_FAIL = "UPDATE_EVENT_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_RESET = "DELETE_EVENT_RESET";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const EVENT_DETAILS_REQUEST = "EVENT_DETAILS_REQUEST";
export const EVENT_DETAILS_SUCCESS = "EVENT_DETAILS_SUCCESS";
export const EVENT_DETAILS_FAIL = "EVENT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"