
export const ALL_REVIEW_REQUEST = "ALL_REVIEWE_REQUEST"
export const ALL_REVIEW_SUCCESS = "ALL_REVIEWE_SUCCESS"
export const ALL_REVIEW_FAIL = "ALL_REVIEWE_FAIL"
export const ALL_REVIEW_RESET = "ALL_REVIEWE_RESET"

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEWE_REQUEST"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEWE_SUCCESS"
export const DELETE_REVIEW_FAIL = "DELETE_REVIEWE_FAIL"
export const DELETE_REVIEW_RESET = "DELETE_REVIEWE_RESET"

export const NEW_REVIEW_REQUEST = "NEW_REVIEWE_REQUEST"
export const NEW_REVIEW_SUCCESS = "NEW_REVIEWE_SUCCESS"
export const NEW_REVIEW_FAIL = "NEW_REVIEWE_FAIL"
export const NEW_REVIEW_RESET = "NEW_REVIEWE_RESET"

export const ALL_VENUE_REQUEST = "ALL_VENUE_REQUEST"
export const ALL_VENUE_SUCCESS = "ALL_VENUE_SUCCESS"
export const ALL_VENUE_FAIL = "ALL_VENUE_FAIL"

export const UPDATE_VENUE_REQUEST = "UPDATE_VENUE_REQUEST"
export const UPDATE_VENUE_SUCCESS = "UPDATE_VENUE_SUCCESS"
export const UPDATE_VENUE_FAIL = "UPDATE_VENUE_FAIL"
export const UPDATE_VENUE_RESET = "UPDATE_VENUE_RESET"

export const DELETE_VENUE_REQUEST = "DELETE_VENUE_REQUEST"
export const DELETE_VENUE_SUCCESS = "DELETE_VENUE_SUCCESS"
export const DELETE_VENUE_FAIL = "DELETE_VENUE_FAIL"
export const DELETE_VENUE_RESET = "DELETE_VENUE_RESET"

export const CREATE_VENUE_REQUEST = "CREATE_VENUE_REQUEST"
export const CREATE_VENUE_SUCCESS = "CREATE_VENUE_SUCCESS"
export const CREATE_VENUE_FAIL = "CREATE_VENUE_FAIL"
export const CREATE_VENUE_RESET = "CREATE_VENUE_RESET"

export const MANAGER_VENUE_REQUEST = "MANAGER_VENUE_REQUEST"
export const MANAGER_VENUE_SUCCESS = "MANAGER_VENUE_SUCCESS"
export const MANAGER_VENUE_FAIL = "MANAGER_VENUE_FAIL"

export const ADMIN_VENUE_REQUEST = "ADMIN_VENUE_REQUEST"
export const ADMIN_VENUE_SUCCESS = "ADMIN_VENUE_SUCCESS"
export const ADMIN_VENUE_FAIL = "ADMIN_VENUE_FAIL"

export const VENUE_DETAILS_REQUEST = "VENUE_DETAILS_REQUEST"
export const VENUE_DETAILS_SUCCESS = "VENUE_DETAILS_SUCCESS"
export const VENUE_DETAILS_FAIL = "VENUE_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"